#!/bin/bash
#
# ******************************************************************************
# *                            cloudFPGA
# *            All rights reserved -- Property of IBM
# *-----------------------------------------------------------------------------
# * 
# * Description : A bash script to start vivado in gui mode and that sets the 
# *   the XPR project to open. An optional Tcl script might also be sourced. 
# * 
# * Synopsis : ./<this_file>
# *
# ******************************************************************************

cd ../xpr

# Set PROJECT_NAME
#-------------------------------------------------------------------------------
XPR_PROJECT="topFMKU60_Flash.xpr"

# Set XDC SETTINGS
#-------------------------------------------------------------------------------
XDC_SETTINGS="YouNameIt.tcl"

# Start Vivado in GUI mode
#  Synopsis: vivado $XPR_PROJECT -source $XDC_SETTINGS
#-------------------------------------------------------------------------------
vivado $XPR_PROJECT & 
