// *****************************************************************************
// *
// *                             cloudFPGA
// *            All rights reserved -- Property of IBM
// *
// *----------------------------------------------------------------------------
// *
// * Title : Toplevel of the echo application in store-and-forward mode.
// *
// * File    : RoleEchoStoreAndForward.v
// *
// * Created : June 2018
// * Authors : Francois Abel <fab@zurich.ibm.com>
// *
// * Devices : xcku060-ffva1156-2-i
// * Tools   : Vivado v2017.4 (64-bit)
// * Depends : None
// *
// * Description : This version of the role implements an echo application 
// *    between the Rx and Tx ports of a UDP connection and between the the Rx
// *    and Tx ports of a TCP connection. The role is said to be operating in
// *    "store-and-forward" mode because every received packet is first written
// *    into the DDR4 memory before being read and sent back on the network.          
// * 
// * Infos & Conventions:
// *    <pi> stands for "PortIn". 
// *    <po> stands for "PortOut".
// *    <pi><SRC>_<Itf1>_<Itf1.1>_<Itf1.1.1>_tdata stands for the "data" signals
// *         of an Axi4-Stream generated by the source (i.e. master) "SRC", out
// *         of its interface "Itf1" and its sub-interfaces "Itf1.1" and 
// *         "Itf1.1.1".
// *    <si> stands for "StreamIn". 
// *    <so> stands for "StreamOut".
// *    <si><SRC>_<Itf1>_<Itf1.1>_<Itf1.1.1>_tdata stands for the "data" signals
// *         of an Axi4-Stream generated by the source (i.e. master) "SRC", out
// *         of its interface "Itf1" and its sub-interfaces "Itf1.1" and 
// *         "Itf1.1.1".
// *
// *****************************************************************************


`timescale 1 ns / 1 ps

// *****************************************************************************
// **  MODULE - ECHO STORE-AND-FORWARD ROLE FOR FMKU60
// *****************************************************************************

module Role_x1Udp_x1Tcp_x2Mp
(

    //------------------------------------------------------
    //-- SHELL / Global Input Clock and Reset Interface
    //------------------------------------------------------
    input wire          piSHL_156_25Clk,
    input wire          piSHL_156_25Rst,

    //--------------------------------------------------------
    //-- SHELL / Role / Nts0 / Udp Interface
    //--------------------------------------------------------
    //---- Input AXI-Write Stream Interface --------
    input wire [ 63:0]  piSHL_Rol_Nts0_Udp_Axis_tdata,
    input wire [ 7:0]   piSHL_Rol_Nts0_Udp_Axis_tkeep,
    input wire          piSHL_Rol_Nts0_Udp_Axis_tlast,
    input wire          piSHL_Rol_Nts0_Udp_Axis_tvalid,
    output wire         poROL_Shl_Nts0_Udp_Axis_tready,
    //---- Output AXI-Write Stream Interface ---------
    input wire          piSHL_Rol_Nts0_Udp_Axis_tready,
    output wire [ 63:0] poROL_Shl_Nts0_Udp_Axis_tdata,
    output wire [ 7:0]  poROL_Shl_Nts0_Udp_Axis_tkeep,
    output wire         poROL_Shl_Nts0_Udp_Axis_tlast,
    output wire         poROL_Shl_Nts0_Udp_Axis_tvalid,
    
    //--------------------------------------------------------
    //-- SHELL / Role / Nts0 / Tcp Interface
    //--------------------------------------------------------
    //---- Input AXI-Write Stream Interface ----------
    input wire [ 63:0]  piSHL_Rol_Nts0_Tcp_Axis_tdata,
    input wire [ 7:0]   piSHL_Rol_Nts0_Tcp_Axis_tkeep,
    input wire          piSHL_Rol_Nts0_Tcp_Axis_tlast,
    input wire          piSHL_Rol_Nts0_Tcp_Axis_tvalid,
    output wire         poROL_Shl_Nts0_Tcp_Axis_tready,
    //---- Output AXI-Write Stream Interface ---------
    input wire          piSHL_Rol_Nts0_Tcp_Axis_tready,
    output wire [ 63:0] poROL_Shl_Nts0_Tcp_Axis_tdata,
    output wire [ 7:0]  poROL_Shl_Nts0_Tcp_Axis_tkeep,
    output wire         poROL_Shl_Nts0_Tcp_Axis_tlast,
    output wire         poROL_Shl_Nts0_Tcp_Axis_tvalid,
    
    //-------------------------------------------------------
    //-- ROLE EMIF Registers
    //-------------------------------------------------------
    output wire         poROL_SHL_EMIF_2B_Reg,
    input wire          piSHL_ROL_EMIF_2B_Reg,
    
    //-----------------------------------------------
    //-- SHELL / Role / Mem / Mp0 Interface
    //------------------------------------------------
    //---- Memory Port #0 / S2MM-AXIS ------------------   
    //------ Stream Read Command -----------------
    input wire          piSHL_Rol_Mem_Mp0_Axis_RdCmd_tready,
    output wire [ 71:0] poROL_Shl_Mem_Mp0_Axis_RdCmd_tdata,
    output wire         poROL_Shl_Mem_Mp0_Axis_RdCmd_tvalid,
    //------ Stream Read Status ------------------
    input wire  [  7:0] piSHL_Rol_Mem_Mp0_Axis_RdSts_tdata,
    input wire          piSHL_Rol_Mem_Mp0_Axis_RdSts_tvalid,
    output wire         poROL_Shl_Mem_Mp0_Axis_RdSts_tready,
    //------ Stream Data Input Channel -----------
    input wire  [511:0] piSHL_Rol_Mem_Mp0_Axis_Read_tdata,
    input wire  [ 63:0] piSHL_Rol_Mem_Mp0_Axis_Read_tkeep,
    input wire          piSHL_Rol_Mem_Mp0_Axis_Read_tlast,
    input wire          piSHL_Rol_Mem_Mp0_Axis_Read_tvalid,
    output wire         poROL_Shl_Mem_Mp0_Axis_Read_tready,
    //------ Stream Write Command ----------------
    input wire          piSHL_Rol_Mem_Mp0_Axis_WrCmd_tready,
    output wire [ 71:0] poROL_Shl_Mem_Mp0_Axis_WrCmd_tdata,
    output wire         poROL_Shl_Mem_Mp0_Axis_WrCmd_tvalid,
    //------ Stream Write Status -----------------
    input wire  [  7:0] piSHL_Rol_Mem_Mp0_Axis_WrSts_tdata,
    input wire          piSHL_Rol_Mem_Mp0_Axis_WrSts_tvalid,
    output wire         poROL_Shl_Mem_Mp0_Axis_WrSts_tready,
    //------ Stream Data Output Channel ----------
    input wire          piSHL_Rol_Mem_Mp0_Axis_Write_tready,
    output wire [511:0] poROL_Shl_Mem_Mp0_Axis_Write_tdata,
    output wire [ 63:0] poROL_Shl_Mem_Mp0_Axis_Write_tkeep,
    output wire         poROL_Shl_Mem_Mp0_Axis_Write_tlast,
    output wire         poROL_Shl_Mem_Mp0_Axis_Write_tvalid,
       
    //------------------------------------------------
    //-- SHELL / Role / Mem / Mp1 Interface
    //------------------------------------------------
    //---- Memory Port #1 / S2MM-AXIS ------------------   
    //------ Stream Read Command -----------------
    input wire          piSHL_Rol_Mem_Mp1_Axis_RdCmd_tready,
    output wire [ 71:0] poROL_Shl_Mem_Mp1_Axis_RdCmd_tdata,
    output wire         poROL_Shl_Mem_Mp1_Axis_RdCmd_tvalid,
    //------ Stream Read Status ------------------
    input wire  [  7:0] piSHL_Rol_Mem_Mp1_Axis_RdSts_tdata,
    input wire          piSHL_Rol_Mem_Mp1_Axis_RdSts_tvalid,
    output wire         poROL_Shl_Mem_Mp1_Axis_RdSts_tready,
    //------ Stream Data Input Channel -----------
    input wire  [511:0] piSHL_Rol_Mem_Mp1_Axis_Read_tdata,
    input wire  [ 63:0] piSHL_Rol_Mem_Mp1_Axis_Read_tkeep,
    input wire          piSHL_Rol_Mem_Mp1_Axis_Read_tlast,
    input wire          piSHL_Rol_Mem_Mp1_Axis_Read_tvalid,
    output wire         poROL_Shl_Mem_Mp1_Axis_Read_tready,
    //------ Stream Write Command ----------------
    input wire          piSHL_Rol_Mem_Mp1_Axis_WrCmd_tready,
    output wire [ 71:0] poROL_Shl_Mem_Mp1_Axis_WrCmd_tdata,
    output wire         poROL_Shl_Mem_Mp1_Axis_WrCmd_tvalid,
    //------ Stream Write Status -----------------
    input wire          piSHL_Rol_Mem_Mp1_Axis_WrSts_tvalid,
    input wire  [  7:0] piSHL_Rol_Mem_Mp1_Axis_WrSts_tdata,
    output wire         poROL_Shl_Mem_Mp1_Axis_WrSts_tready,
    //------ Stream Data Output Channel ----------
    input wire          piSHL_Rol_Mem_Mp1_Axis_Write_tready,
    output wire [511:0] poROL_Shl_Mem_Mp1_Axis_Write_tdata,
    output wire [ 63:0] poROL_Shl_Mem_Mp1_Axis_Write_tkeep,
    output wire         poROL_Shl_Mem_Mp1_Axis_Write_tlast,
    output wire         poROL_Shl_Mem_Mp1_Axis_Write_tvalid,
    
    //------------------------------------------------
    //-- TOP : Secondary Clock (Asynchronous)
    //------------------------------------------------
    input wire          piTOP_250_00Clk,
       
    output wire         poVoid

);


// *****************************************************************************
// **  STRUCTURE
// *****************************************************************************

  //============================================================================
  //  SIGNAL (i.e. WIRES & REGISTERS) DECLARATIONS
  //============================================================================
 

   //============================================================================
  //  INST: EchoStoreAndForward
  //============================================================================
  EchoStoreAndForward ECHO (

    //------------------------------------------------------
	//-- SHELL / Role / Nts0 / Udp Interface
	//------------------------------------------------------                            
    //---- Input AXI-Write Stream Interface --------
    .siUdp_TDATA           (piSHL_Rol_Nts0_Udp_Axis_tdata),
    .siUdp_TKEEP           (piSHL_Rol_Nts0_Udp_Axis_tkeep),
    .siUdp_TLAST           (piSHL_Rol_Nts0_Udp_Axis_tlast),
    .siUdp_TVALID          (piSHL_Rol_Nts0_Udp_Axis_tvalid),
    .siUdp_TREADY          (poROL_Shl_Nts0_Udp_Axis_tready),
    //---- Output AXI-Write Stream Interface ---------
    .soUdp_TREADY          (piSHL_Rol_Nts0_Udp_Axis_tready),
    .soUdp_TDATA           (poROL_Shl_Nts0_Udp_Axis_tdata),
    .soUdp_TKEEP           (poROL_Shl_Nts0_Udp_Axis_tkeep),
    .soUdp_TLAST           (poROL_Shl_Nts0_Udp_Axis_tlast),
    .soUdp_TVALID          (poROL_Shl_Nts0_Udp_Axis_tvalid),
     
    //------------------------------------------------------
    //-- SHELL / Role / Nts0 / Udp Interface
	  //------------------------------------------------------                            
    //---- Input AXI-Write Stream Interface --------
    .si_Tcp_TDATA          (piSHL_Rol_Nts0_Tcp_Axis_tdata),
    .si_Tcp_TKEEP          (piSHL_Rol_Nts0_Tcp_Axis_tkeep),
    .si_Tcp_TLAST          (piSHL_Rol_Nts0_Tcp_Axis_tlast),
    .si_Tcp_TVALID         (piSHL_Rol_Nts0_Tcp_Axis_tvalid),
    .si_Tcp_TREADY         (poROL_Shl_Nts0_Tcp_Axis_tready),
    //---- Output AXI-Write Stream Interface ---------
    .so_Tcp_TREADY         (piSHL_Rol_Nts0_Tcp_Axis_tready),
    .so_Tcp_TDATA          (poROL_Shl_Nts0_Tcp_Axis_tdata),
    .so_Tcp_TKEEP          (poROL_Shl_Nts0_Tcp_Axis_tkeep),
    .so_Tcp_TLAST          (poROL_Shl_Nts0_Tcp_Axis_tlast),
    .so_Tcp_TVALID         (poROL_Shl_Nts0_Tcp_Axis_tvalid),
                        
	  //------------------------------------------------------
	  //-- SHELL / Role / Mem / Mp0 Interface
	  //------------------------------------------------------
	  //---- Read Path (MM2S) ------------
    .soMemRdCmdP0_V_TREADY (piSHL_Rol_Mem_Mp0_Axis_RdCmd_tready),
    .soMemRdCmdP0_V_TDATA  (poROL_Shl_Mem_Mp0_Axis_RdCmd_tdata),
    .soMemRdCmdP0_V_TVALID (poROL_Shl_Mem_Mp0_Axis_RdCmd_tvalid),
 
    .siMemRdStsP0_V_TVALID (piSHL_Rol_Mem_Mp0_Axis_RdSts_tvalid),
    .siMemRdStsP0_V_TDATA  (piSHL_Rol_Mem_Mp0_Axis_RdSts_tdata),
    .siMemRdStsP0_V_TREADY (poROL_Shl_Mem_Mp0_Axis_RdSts_tready),
                            
    .siMemReadP0_DATA      (piSHL_Rol_Mem_Mp0_Axis_Read_tdata),
    .siMemReadP0_TKEEP     (piSHL_Rol_Mem_Mp0_Axis_Read_tkeep),
    .siMemReadP0_TLAST     (piSHL_Rol_Mem_Mp0_Axis_Read_tlast),
    .siMemReadP0_TVALID    (piSHL_Rol_Mem_Mp0_Axis_Read_tvalid),
    .siMemReadP0_TREADY    (poROL_Shl_Mem_Mp0_Axis_Read_tready),
	  //---- Write Path (S2MM) -----------
    .soMemWrCmdP0_V_TREADY (piSHL_Rol_Mem_Mp0_Axis_WrCmd_tready),
    .soMemWrCmdP0_V_TDATA  (poROL_Shl_Mem_Mp0_Axis_WrCmd_tdata),
    .soMemWrCmdP0_V_TVALID (poROL_Shl_Mem_Mp0_Axis_WrCmd_tvalid),
                            
    .siMemWrStsP0_V_TDATA  (piSHL_Rol_Mem_Mp0_Axis_WrSts_tdata),
    .siMemWrStsP0_V_TVALID (piSHL_Rol_Mem_Mp0_Axis_WrSts_tvalid),
    .siMemWrStsP0_V_TREADY (poROL_Shl_Mem_Mp0_Axis_WrSts_tready),

    .soMemWriteP0_TDATA    (poROL_Shl_Mem_Mp0_Axis_Write_tdata),
    .soMemWriteP0_TKEEP    (poROL_Shl_Mem_Mp0_Axis_Write_tkeep),
    .soMemWriteP0_TLAST    (poROL_Shl_Mem_Mp0_Axis_Write_tlast),
    .soMemWriteP0_TVALID   (poROL_Shl_Mem_Mp0_Axis_Write_tvalid),
    .soMemWriteP0_TREADY   (piSHL_Rol_Mem_Mp0_Axis_Write_tready),
    
	  //------------------------------------------------------
	  //-- SHELL / Role / Mem / Mp1 Interface
	  //------------------------------------------------------
	  //---- Read Path (MM2S) ------------
    .soMemRdCmdP1_V_TREADY (piSHL_Rol_Mem_Mp1_Axis_RdCmd_tready),
    .soMemRdCmdP1_V_TDATA  (poROL_Shl_Mem_Mp1_Axis_RdCmd_tdata),
    .soMemRdCmdP1_V_TVALID (poROL_Shl_Mem_Mp1_Axis_RdCmd_tvalid),

    .siMemRdStsP1_V_TDATA  (piSHL_Rol_Mem_Mp1_Axis_RdSts_tdata),
    .siMemRdStsP1_V_TVALID (piSHL_Rol_Mem_Mp1_Axis_RdSts_tvalid),
    .siMemRdStsP1_V_TREADY (poROL_Shl_Mem_Mp1_Axis_RdSts_tready),

    .siMemReadP1_TDATA     (piSHL_Rol_Mem_Mp1_Axis_Read_tdata),
    .siMemReadP1_TKEEP     (piSHL_Rol_Mem_Mp1_Axis_Read_tkeep),
    .siMemReadP1_TLAST     (piSHL_Rol_Mem_Mp1_Axis_Read_tlast),
    .siMemReadP1_TVALID    (piSHL_Rol_Mem_Mp1_Axis_Read_tvalid),
    .siMemReadP1_TREADY    (poROL_Shl_Mem_Mp1_Axis_Read_tready),
	  //---- Write Path (S2MM) -----------
    .soMemWrCmdP1_V_TREADY (piSHL_Rol_Mem_Mp1_Axis_WrCmd_tready),
    .soMemWrCmdP1_V_TDATA  (poROL_Shl_Mem_Mp1_Axis_WrCmd_tdata),
    .soMemWrCmdP1_V_TVALID (poROL_Shl_Mem_Mp1_Axis_WrCmd_tvalid),

    .siMemWrStsP1_V_TDATA  (piSHL_Rol_Mem_Mp1_Axis_WrSts_tdata),
    .siMemWrStsP1_V_TVALID (piSHL_Rol_Mem_Mp1_Axis_WrSts_tvalid),
    .siMemWrStsP1_V_TREADY (poROL_Shl_Mem_Mp1_Axis_WrSts_tready),

    .soMemWriteP1_V_TDATA  (poROL_Shl_Mem_Mp1_Axis_Write_tdata),
    .soMemWriteP1_V_TKEEP  (poROL_Shl_Mem_Mp1_Axis_Write_tkeep),
    .soMemWriteP1_V_TLAST  (poROL_Shl_Mem_Mp1_Axis_Write_tlast),
    .soMemWriteP1_V_TVALID (poROL_Shl_Mem_Mp1_Axis_Write_tvalid),
    .soMemWriteP1_V_TREADY (piSHL_Rol_Mem_Mp1_Axis_Write_tready),
                        
    //------------------------------------------------------
    //-- SHELL / Global Input Clock and Reset Interface
    //------------------------------------------------------
    .aclk                  (piSHL_156_25Clk),
    .aresetn               (~piSHL_156_25Rst)
 
  );  // End of ECHO


endmodule

