// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.3
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module icmp_server_insertChecksum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        checksumStreams_V_V_0_dout,
        checksumStreams_V_V_0_empty_n,
        checksumStreams_V_V_0_read,
        checksumStreams_V_V_1_dout,
        checksumStreams_V_V_1_empty_n,
        checksumStreams_V_V_1_read,
        outputStream_V_data_V_din,
        outputStream_V_data_V_full_n,
        outputStream_V_data_V_write,
        outputStream_V_keep_V_din,
        outputStream_V_keep_V_full_n,
        outputStream_V_keep_V_write,
        outputStream_V_last_V_din,
        outputStream_V_last_V_full_n,
        outputStream_V_last_V_write,
        dataStreams_V_data_V_0_dout,
        dataStreams_V_data_V_0_empty_n,
        dataStreams_V_data_V_0_read,
        dataStreams_V_keep_V_0_dout,
        dataStreams_V_keep_V_0_empty_n,
        dataStreams_V_keep_V_0_read,
        dataStreams_V_last_V_0_dout,
        dataStreams_V_last_V_0_empty_n,
        dataStreams_V_last_V_0_read,
        dataStreams_V_data_V_1_dout,
        dataStreams_V_data_V_1_empty_n,
        dataStreams_V_data_V_1_read,
        dataStreams_V_keep_V_1_dout,
        dataStreams_V_keep_V_1_empty_n,
        dataStreams_V_keep_V_1_read,
        dataStreams_V_last_V_1_dout,
        dataStreams_V_last_V_1_empty_n,
        dataStreams_V_last_V_1_read
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_pp0_stg0_fsm_0 = 1'b0;
parameter    ap_const_lv16_2 = 16'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv16_3 = 16'b11;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] checksumStreams_V_V_0_dout;
input   checksumStreams_V_V_0_empty_n;
output   checksumStreams_V_V_0_read;
input  [15:0] checksumStreams_V_V_1_dout;
input   checksumStreams_V_V_1_empty_n;
output   checksumStreams_V_V_1_read;
output  [63:0] outputStream_V_data_V_din;
input   outputStream_V_data_V_full_n;
output   outputStream_V_data_V_write;
output  [7:0] outputStream_V_keep_V_din;
input   outputStream_V_keep_V_full_n;
output   outputStream_V_keep_V_write;
output  [0:0] outputStream_V_last_V_din;
input   outputStream_V_last_V_full_n;
output   outputStream_V_last_V_write;
input  [63:0] dataStreams_V_data_V_0_dout;
input   dataStreams_V_data_V_0_empty_n;
output   dataStreams_V_data_V_0_read;
input  [7:0] dataStreams_V_keep_V_0_dout;
input   dataStreams_V_keep_V_0_empty_n;
output   dataStreams_V_keep_V_0_read;
input  [0:0] dataStreams_V_last_V_0_dout;
input   dataStreams_V_last_V_0_empty_n;
output   dataStreams_V_last_V_0_read;
input  [63:0] dataStreams_V_data_V_1_dout;
input   dataStreams_V_data_V_1_empty_n;
output   dataStreams_V_data_V_1_read;
input  [7:0] dataStreams_V_keep_V_1_dout;
input   dataStreams_V_keep_V_1_empty_n;
output   dataStreams_V_keep_V_1_read;
input  [0:0] dataStreams_V_last_V_1_dout;
input   dataStreams_V_last_V_1_empty_n;
output   dataStreams_V_last_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg checksumStreams_V_V_0_read;
reg checksumStreams_V_V_1_read;
reg[63:0] outputStream_V_data_V_din;
reg[7:0] outputStream_V_keep_V_din;
reg[0:0] outputStream_V_last_V_din;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "auto" *) reg   [0:0] ap_CS_fsm = 1'b0;
wire    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire    dataStreams_V_data_V_00_status;
reg   [0:0] tmp_4_phi_fu_202_p4;
reg   [0:0] tmp_5_phi_fu_214_p4;
wire    dataStreams_V_data_V_10_status;
wire   [0:0] brmerge_fu_403_p2;
wire   [0:0] grp_nbreadreq_fu_114_p5;
reg   [0:0] tmp_phi_fu_226_p4;
reg    ap_sig_bdd_101;
wire    outputStream_V_data_V1_status;
reg   [15:0] t_V_reg_460;
reg   [0:0] tmp_4_reg_199;
reg   [0:0] tmp_5_reg_211;
reg   [0:0] brmerge_reg_490;
reg   [0:0] tmp_reg_223;
reg    ap_sig_bdd_132;
reg   [15:0] ic_wordCount_V = 16'b0000000000000000;
reg   [0:0] streamSource_V_1 = 1'b0;
reg   [0:0] tmp_last_V_5_reg_235;
wire   [0:0] grp_nbreadreq_fu_126_p5;
wire   [0:0] ap_reg_phiprechg_tmp_4_reg_199pp0_it0;
wire   [0:0] tmp_8_nbreadreq_fu_138_p3;
wire   [0:0] ap_reg_phiprechg_tmp_5_reg_211pp0_it0;
wire   [0:0] tmp_7_nbreadreq_fu_146_p3;
wire   [0:0] ap_reg_phiprechg_tmp_reg_223pp0_it0;
wire   [0:0] ap_reg_phiprechg_tmp_last_V_5_reg_235pp0_it0;
reg   [0:0] tmp_last_V_5_phi_fu_239_p4;
wire   [0:0] ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it0;
reg   [0:0] ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it1;
wire   [7:0] ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it0;
reg   [7:0] ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it1;
wire   [63:0] ap_reg_phiprechg_p_Val2_s_reg_266pp0_it0;
reg   [63:0] ap_reg_phiprechg_p_Val2_s_reg_266pp0_it1;
wire   [15:0] ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it0;
reg   [15:0] ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it1;
wire   [0:0] ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it0;
reg   [0:0] ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it1;
wire   [7:0] ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it0;
reg   [7:0] ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it1;
wire   [63:0] ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it0;
reg   [63:0] ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it1;
wire   [7:0] ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it0;
reg   [7:0] ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it1;
wire   [63:0] ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it0;
reg   [63:0] ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it1;
reg    dataStreams_V_data_V_00_update;
reg    dataStreams_V_data_V_10_update;
reg    outputStream_V_data_V1_update;
wire   [63:0] p_Result_s_fu_447_p5;
wire   [15:0] p_tmp_s_fu_433_p3;
wire   [0:0] not_tmp_s_fu_409_p2;
wire   [15:0] tmp_9_fu_427_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_pprstidle_pp0;
reg    ap_sig_bdd_52;
reg    ap_sig_bdd_45;
reg    ap_sig_bdd_139;
reg    ap_sig_bdd_74;
reg    ap_sig_bdd_77;
reg    ap_sig_bdd_89;
reg    ap_sig_bdd_86;
reg    ap_sig_bdd_316;
reg    ap_sig_bdd_71;
reg    ap_sig_bdd_321;
reg    ap_sig_bdd_115;
reg    ap_sig_bdd_121;
reg    ap_sig_bdd_129;
reg    ap_sig_bdd_258;
reg    ap_sig_bdd_422;
reg    ap_sig_bdd_50;
reg    ap_sig_bdd_37;
reg    ap_sig_bdd_426;
reg    ap_sig_bdd_41;
reg    ap_sig_bdd_51;
reg    ap_sig_bdd_432;
reg    ap_sig_bdd_431;
reg    ap_sig_bdd_88;
reg    ap_sig_bdd_82;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_45) begin
            ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it1 <= checksumStreams_V_V_0_dout;
        end else if (ap_sig_bdd_52) begin
            ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it1 <= checksumStreams_V_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it1 <= ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_45) begin
            ap_reg_phiprechg_p_Val2_s_reg_266pp0_it1 <= dataStreams_V_data_V_0_dout;
        end else if (ap_sig_bdd_52) begin
            ap_reg_phiprechg_p_Val2_s_reg_266pp0_it1 <= dataStreams_V_data_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_p_Val2_s_reg_266pp0_it1 <= ap_reg_phiprechg_p_Val2_s_reg_266pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_77) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it1 <= dataStreams_V_data_V_0_dout;
        end else if (ap_sig_bdd_74) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it1 <= dataStreams_V_data_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it1 <= ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_86) begin
            ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it1 <= dataStreams_V_data_V_0_dout;
        end else if (ap_sig_bdd_89) begin
            ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it1 <= dataStreams_V_data_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it1 <= ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_77) begin
            ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it1 <= dataStreams_V_keep_V_0_dout;
        end else if (ap_sig_bdd_74) begin
            ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it1 <= dataStreams_V_keep_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it1 <= ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_86) begin
            ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it1 <= dataStreams_V_keep_V_0_dout;
        end else if (ap_sig_bdd_89) begin
            ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it1 <= dataStreams_V_keep_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it1 <= ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_45) begin
            ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it1 <= dataStreams_V_keep_V_0_dout;
        end else if (ap_sig_bdd_52) begin
            ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it1 <= dataStreams_V_keep_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it1 <= ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_77) begin
            ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it1 <= dataStreams_V_last_V_0_dout;
        end else if (ap_sig_bdd_74) begin
            ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it1 <= dataStreams_V_last_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it1 <= ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_45) begin
            ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it1 <= dataStreams_V_last_V_0_dout;
        end else if (ap_sig_bdd_52) begin
            ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it1 <= dataStreams_V_last_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it1 <= ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_321) begin
            ic_wordCount_V <= p_tmp_s_fu_433_p3;
        end else if (ap_sig_bdd_71) begin
            ic_wordCount_V <= ap_const_lv16_1;
        end else if (ap_sig_bdd_316) begin
            ic_wordCount_V <= ap_const_lv16_3;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_37) begin
            tmp_4_reg_199 <= grp_nbreadreq_fu_114_p5;
        end else if (ap_sig_bdd_50) begin
            tmp_4_reg_199 <= grp_nbreadreq_fu_126_p5;
        end else if ((ap_true == ap_true)) begin
            tmp_4_reg_199 <= ap_reg_phiprechg_tmp_4_reg_199pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_51) begin
            tmp_5_reg_211 <= tmp_7_nbreadreq_fu_146_p3;
        end else if (ap_sig_bdd_41) begin
            tmp_5_reg_211 <= tmp_8_nbreadreq_fu_138_p3;
        end else if ((ap_true == ap_true)) begin
            tmp_5_reg_211 <= ap_reg_phiprechg_tmp_5_reg_211pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_86) begin
            tmp_last_V_5_reg_235 <= dataStreams_V_last_V_0_dout;
        end else if (ap_sig_bdd_89) begin
            tmp_last_V_5_reg_235 <= dataStreams_V_last_V_1_dout;
        end else if ((ap_true == ap_true)) begin
            tmp_last_V_5_reg_235 <= ap_reg_phiprechg_tmp_last_V_5_reg_235pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_139) begin
        if (ap_sig_bdd_82) begin
            tmp_reg_223 <= grp_nbreadreq_fu_114_p5;
        end else if (ap_sig_bdd_88) begin
            tmp_reg_223 <= grp_nbreadreq_fu_126_p5;
        end else if ((ap_true == ap_true)) begin
            tmp_reg_223 <= ap_reg_phiprechg_tmp_reg_223pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ic_wordCount_V == ap_const_lv16_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        brmerge_reg_490 <= brmerge_fu_403_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        streamSource_V_1 <= not_tmp_s_fu_409_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        t_V_reg_460 <= ic_wordCount_V;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_101 or ap_sig_bdd_132)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it1))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_101 or ap_sig_bdd_132)
begin
    if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_pprstidle_pp0 assign process. ///
always @ (ap_start or ap_reg_ppiten_pp0_it0)
begin
    if (((ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_start))) begin
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    end else begin
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    end
end

/// checksumStreams_V_V_0_read assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or ap_sig_bdd_101 or ap_sig_bdd_132 or ic_wordCount_V or streamSource_V_1)
begin
    if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_2) & (streamSource_V_1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        checksumStreams_V_V_0_read = ap_const_logic_1;
    end else begin
        checksumStreams_V_V_0_read = ap_const_logic_0;
    end
end

/// checksumStreams_V_V_1_read assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or ap_sig_bdd_101 or ap_sig_bdd_132 or ic_wordCount_V or streamSource_V_1)
begin
    if (((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & ~(streamSource_V_1 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        checksumStreams_V_V_1_read = ap_const_logic_1;
    end else begin
        checksumStreams_V_V_1_read = ap_const_logic_0;
    end
end

/// dataStreams_V_data_V_00_update assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or brmerge_fu_403_p2 or grp_nbreadreq_fu_114_p5 or tmp_phi_fu_226_p4 or ap_sig_bdd_101 or ap_sig_bdd_132 or ic_wordCount_V or streamSource_V_1)
begin
    if ((((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_2) & (streamSource_V_1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2) & ~(ap_const_lv1_0 == grp_nbreadreq_fu_114_p5) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        dataStreams_V_data_V_00_update = ap_const_logic_1;
    end else begin
        dataStreams_V_data_V_00_update = ap_const_logic_0;
    end
end

/// dataStreams_V_data_V_10_update assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or brmerge_fu_403_p2 or grp_nbreadreq_fu_114_p5 or tmp_phi_fu_226_p4 or ap_sig_bdd_101 or ap_sig_bdd_132 or ic_wordCount_V or streamSource_V_1)
begin
    if ((((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & ~(streamSource_V_1 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2) & (ap_const_lv1_0 == grp_nbreadreq_fu_114_p5) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        dataStreams_V_data_V_10_update = ap_const_logic_1;
    end else begin
        dataStreams_V_data_V_10_update = ap_const_logic_0;
    end
end

/// outputStream_V_data_V1_update assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_101 or t_V_reg_460 or tmp_4_reg_199 or tmp_5_reg_211 or brmerge_reg_490 or tmp_reg_223 or ap_sig_bdd_132)
begin
    if ((((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_lv16_2 == t_V_reg_460) & ~(ap_const_lv1_0 == tmp_4_reg_199) & ~(ap_const_lv1_0 == tmp_5_reg_211) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_lv16_0 == t_V_reg_460) & ~(ap_const_lv1_0 == brmerge_reg_490) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & ~(ap_const_lv16_2 == t_V_reg_460) & ~(ap_const_lv16_0 == t_V_reg_460) & ~(ap_const_lv1_0 == tmp_reg_223) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        outputStream_V_data_V1_update = ap_const_logic_1;
    end else begin
        outputStream_V_data_V1_update = ap_const_logic_0;
    end
end

/// outputStream_V_data_V_din assign process. ///
always @ (ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it1 or ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it1 or p_Result_s_fu_447_p5 or ap_sig_bdd_115 or ap_sig_bdd_121 or ap_sig_bdd_129 or ap_sig_bdd_258)
begin
    if (ap_sig_bdd_258) begin
        if (ap_sig_bdd_129) begin
            outputStream_V_data_V_din = ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it1;
        end else if (ap_sig_bdd_121) begin
            outputStream_V_data_V_din = ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it1;
        end else if (ap_sig_bdd_115) begin
            outputStream_V_data_V_din = p_Result_s_fu_447_p5;
        end else begin
            outputStream_V_data_V_din = 'bx;
        end
    end else begin
        outputStream_V_data_V_din = 'bx;
    end
end

/// outputStream_V_keep_V_din assign process. ///
always @ (ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it1 or ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it1 or ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it1 or ap_sig_bdd_115 or ap_sig_bdd_121 or ap_sig_bdd_129 or ap_sig_bdd_258)
begin
    if (ap_sig_bdd_258) begin
        if (ap_sig_bdd_129) begin
            outputStream_V_keep_V_din = ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it1;
        end else if (ap_sig_bdd_121) begin
            outputStream_V_keep_V_din = ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it1;
        end else if (ap_sig_bdd_115) begin
            outputStream_V_keep_V_din = ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it1;
        end else begin
            outputStream_V_keep_V_din = 'bx;
        end
    end else begin
        outputStream_V_keep_V_din = 'bx;
    end
end

/// outputStream_V_last_V_din assign process. ///
always @ (tmp_last_V_5_reg_235 or ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it1 or ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it1 or ap_sig_bdd_115 or ap_sig_bdd_121 or ap_sig_bdd_129 or ap_sig_bdd_258)
begin
    if (ap_sig_bdd_258) begin
        if (ap_sig_bdd_129) begin
            outputStream_V_last_V_din = tmp_last_V_5_reg_235;
        end else if (ap_sig_bdd_121) begin
            outputStream_V_last_V_din = ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it1;
        end else if (ap_sig_bdd_115) begin
            outputStream_V_last_V_din = ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it1;
        end else begin
            outputStream_V_last_V_din = 'bx;
        end
    end else begin
        outputStream_V_last_V_din = 'bx;
    end
end

/// tmp_4_phi_fu_202_p4 assign process. ///
always @ (grp_nbreadreq_fu_114_p5 or streamSource_V_1 or grp_nbreadreq_fu_126_p5 or ap_reg_phiprechg_tmp_4_reg_199pp0_it0 or ap_sig_bdd_422)
begin
    if (ap_sig_bdd_422) begin
        if ((streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_4_phi_fu_202_p4 = grp_nbreadreq_fu_114_p5;
        end else if (~(streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_4_phi_fu_202_p4 = grp_nbreadreq_fu_126_p5;
        end else begin
            tmp_4_phi_fu_202_p4 = ap_reg_phiprechg_tmp_4_reg_199pp0_it0;
        end
    end else begin
        tmp_4_phi_fu_202_p4 = ap_reg_phiprechg_tmp_4_reg_199pp0_it0;
    end
end

/// tmp_5_phi_fu_214_p4 assign process. ///
always @ (checksumStreams_V_V_0_empty_n or checksumStreams_V_V_1_empty_n or streamSource_V_1 or ap_reg_phiprechg_tmp_5_reg_211pp0_it0 or ap_sig_bdd_426)
begin
    if (ap_sig_bdd_426) begin
        if (~(streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_5_phi_fu_214_p4 = checksumStreams_V_V_1_empty_n;
        end else if ((streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_5_phi_fu_214_p4 = checksumStreams_V_V_0_empty_n;
        end else begin
            tmp_5_phi_fu_214_p4 = ap_reg_phiprechg_tmp_5_reg_211pp0_it0;
        end
    end else begin
        tmp_5_phi_fu_214_p4 = ap_reg_phiprechg_tmp_5_reg_211pp0_it0;
    end
end

/// tmp_last_V_5_phi_fu_239_p4 assign process. ///
always @ (streamSource_V_1 or dataStreams_V_last_V_0_dout or dataStreams_V_last_V_1_dout or ap_reg_phiprechg_tmp_last_V_5_reg_235pp0_it0 or ap_sig_bdd_432)
begin
    if (ap_sig_bdd_432) begin
        if ((streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_last_V_5_phi_fu_239_p4 = dataStreams_V_last_V_0_dout;
        end else if (~(streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_last_V_5_phi_fu_239_p4 = dataStreams_V_last_V_1_dout;
        end else begin
            tmp_last_V_5_phi_fu_239_p4 = ap_reg_phiprechg_tmp_last_V_5_reg_235pp0_it0;
        end
    end else begin
        tmp_last_V_5_phi_fu_239_p4 = ap_reg_phiprechg_tmp_last_V_5_reg_235pp0_it0;
    end
end

/// tmp_phi_fu_226_p4 assign process. ///
always @ (grp_nbreadreq_fu_114_p5 or streamSource_V_1 or grp_nbreadreq_fu_126_p5 or ap_reg_phiprechg_tmp_reg_223pp0_it0 or ap_sig_bdd_431)
begin
    if (ap_sig_bdd_431) begin
        if ((streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_phi_fu_226_p4 = grp_nbreadreq_fu_114_p5;
        end else if (~(streamSource_V_1 == ap_const_lv1_0)) begin
            tmp_phi_fu_226_p4 = grp_nbreadreq_fu_126_p5;
        end else begin
            tmp_phi_fu_226_p4 = ap_reg_phiprechg_tmp_reg_223pp0_it0;
        end
    end else begin
        tmp_phi_fu_226_p4 = ap_reg_phiprechg_tmp_reg_223pp0_it0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_101 or ap_sig_bdd_132 or ap_sig_pprstidle_pp0)
begin
    case (ap_CS_fsm)
        ap_ST_pp0_stg0_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it0 = 'bx;
assign ap_reg_phiprechg_p_Val2_s_reg_266pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_4_reg_199pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_5_reg_211pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_data_V_2_reg_304pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_data_V_5_reg_324pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_keep_V_2_reg_294pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_keep_V_5_reg_314pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_keep_V_8_reg_256pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_last_V_2_reg_284pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_last_V_5_reg_235pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_last_V_8_reg_246pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_reg_223pp0_it0 = 'bx;
assign ap_reg_ppiten_pp0_it0 = ap_start;

/// ap_sig_bdd_101 assign process. ///
always @ (ap_start or ap_done_reg or dataStreams_V_data_V_00_status or tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or dataStreams_V_data_V_10_status or checksumStreams_V_V_0_empty_n or checksumStreams_V_V_1_empty_n or brmerge_fu_403_p2 or grp_nbreadreq_fu_114_p5 or tmp_phi_fu_226_p4 or ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_101 = (((dataStreams_V_data_V_00_status == ap_const_logic_0) & (ic_wordCount_V == ap_const_lv16_2) & (streamSource_V_1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4)) | ((ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & (dataStreams_V_data_V_10_status == ap_const_logic_0) & ~(streamSource_V_1 == ap_const_lv1_0)) | ((ic_wordCount_V == ap_const_lv16_2) & (streamSource_V_1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & (checksumStreams_V_V_0_empty_n == ap_const_logic_0)) | ((ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & ~(streamSource_V_1 == ap_const_lv1_0) & (checksumStreams_V_V_1_empty_n == ap_const_logic_0)) | ((dataStreams_V_data_V_10_status == ap_const_logic_0) & (ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2) & (ap_const_lv1_0 == grp_nbreadreq_fu_114_p5)) | ((dataStreams_V_data_V_00_status == ap_const_logic_0) & (ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2) & ~(ap_const_lv1_0 == grp_nbreadreq_fu_114_p5)) | ((dataStreams_V_data_V_00_status == ap_const_logic_0) & (streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4)) | ((dataStreams_V_data_V_10_status == ap_const_logic_0) & ~(streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4)) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_115 assign process. ///
always @ (t_V_reg_460 or tmp_4_reg_199 or tmp_5_reg_211)
begin
    ap_sig_bdd_115 = ((ap_const_lv16_2 == t_V_reg_460) & ~(ap_const_lv1_0 == tmp_4_reg_199) & ~(ap_const_lv1_0 == tmp_5_reg_211));
end

/// ap_sig_bdd_121 assign process. ///
always @ (t_V_reg_460 or brmerge_reg_490)
begin
    ap_sig_bdd_121 = ((ap_const_lv16_0 == t_V_reg_460) & ~(ap_const_lv1_0 == brmerge_reg_490));
end

/// ap_sig_bdd_129 assign process. ///
always @ (t_V_reg_460 or tmp_reg_223)
begin
    ap_sig_bdd_129 = (~(ap_const_lv16_2 == t_V_reg_460) & ~(ap_const_lv16_0 == t_V_reg_460) & ~(ap_const_lv1_0 == tmp_reg_223));
end

/// ap_sig_bdd_132 assign process. ///
always @ (outputStream_V_data_V1_status or t_V_reg_460 or tmp_4_reg_199 or tmp_5_reg_211 or brmerge_reg_490 or tmp_reg_223)
begin
    ap_sig_bdd_132 = (((outputStream_V_data_V1_status == ap_const_logic_0) & (ap_const_lv16_2 == t_V_reg_460) & ~(ap_const_lv1_0 == tmp_4_reg_199) & ~(ap_const_lv1_0 == tmp_5_reg_211)) | ((outputStream_V_data_V1_status == ap_const_logic_0) & (ap_const_lv16_0 == t_V_reg_460) & ~(ap_const_lv1_0 == brmerge_reg_490)) | ((outputStream_V_data_V1_status == ap_const_logic_0) & ~(ap_const_lv16_2 == t_V_reg_460) & ~(ap_const_lv16_0 == t_V_reg_460) & ~(ap_const_lv1_0 == tmp_reg_223)));
end

/// ap_sig_bdd_139 assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_101 or ap_sig_bdd_132)
begin
    ap_sig_bdd_139 = ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))));
end

/// ap_sig_bdd_258 assign process. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_101 or ap_sig_bdd_132)
begin
    ap_sig_bdd_258 = ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_101) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))));
end

/// ap_sig_bdd_316 assign process. ///
always @ (tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or ic_wordCount_V)
begin
    ap_sig_bdd_316 = ((ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4));
end

/// ap_sig_bdd_321 assign process. ///
always @ (tmp_phi_fu_226_p4 or ic_wordCount_V)
begin
    ap_sig_bdd_321 = (~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4));
end

/// ap_sig_bdd_37 assign process. ///
always @ (ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_37 = ((ic_wordCount_V == ap_const_lv16_2) & (streamSource_V_1 == ap_const_lv1_0));
end

/// ap_sig_bdd_41 assign process. ///
always @ (tmp_4_phi_fu_202_p4 or ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_41 = ((ic_wordCount_V == ap_const_lv16_2) & (streamSource_V_1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4));
end

/// ap_sig_bdd_422 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ic_wordCount_V)
begin
    ap_sig_bdd_422 = ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_2));
end

/// ap_sig_bdd_426 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or tmp_4_phi_fu_202_p4 or ic_wordCount_V)
begin
    ap_sig_bdd_426 = ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4));
end

/// ap_sig_bdd_431 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ic_wordCount_V)
begin
    ap_sig_bdd_431 = ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0));
end

/// ap_sig_bdd_432 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or tmp_phi_fu_226_p4 or ic_wordCount_V)
begin
    ap_sig_bdd_432 = ((ap_ST_pp0_stg0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4));
end

/// ap_sig_bdd_45 assign process. ///
always @ (tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_45 = ((ic_wordCount_V == ap_const_lv16_2) & (streamSource_V_1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4));
end

/// ap_sig_bdd_50 assign process. ///
always @ (ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_50 = ((ic_wordCount_V == ap_const_lv16_2) & ~(streamSource_V_1 == ap_const_lv1_0));
end

/// ap_sig_bdd_51 assign process. ///
always @ (tmp_4_phi_fu_202_p4 or ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_51 = ((ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(streamSource_V_1 == ap_const_lv1_0));
end

/// ap_sig_bdd_52 assign process. ///
always @ (tmp_4_phi_fu_202_p4 or tmp_5_phi_fu_214_p4 or ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_52 = ((ic_wordCount_V == ap_const_lv16_2) & ~(ap_const_lv1_0 == tmp_4_phi_fu_202_p4) & ~(ap_const_lv1_0 == tmp_5_phi_fu_214_p4) & ~(streamSource_V_1 == ap_const_lv1_0));
end

/// ap_sig_bdd_71 assign process. ///
always @ (brmerge_fu_403_p2 or ic_wordCount_V)
begin
    ap_sig_bdd_71 = ((ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2));
end

/// ap_sig_bdd_74 assign process. ///
always @ (brmerge_fu_403_p2 or grp_nbreadreq_fu_114_p5 or ic_wordCount_V)
begin
    ap_sig_bdd_74 = ((ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2) & (ap_const_lv1_0 == grp_nbreadreq_fu_114_p5));
end

/// ap_sig_bdd_77 assign process. ///
always @ (brmerge_fu_403_p2 or grp_nbreadreq_fu_114_p5 or ic_wordCount_V)
begin
    ap_sig_bdd_77 = ((ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == brmerge_fu_403_p2) & ~(ap_const_lv1_0 == grp_nbreadreq_fu_114_p5));
end

/// ap_sig_bdd_82 assign process. ///
always @ (ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_82 = ((streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0));
end

/// ap_sig_bdd_86 assign process. ///
always @ (tmp_phi_fu_226_p4 or ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_86 = ((streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4));
end

/// ap_sig_bdd_88 assign process. ///
always @ (ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_88 = (~(streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0));
end

/// ap_sig_bdd_89 assign process. ///
always @ (tmp_phi_fu_226_p4 or ic_wordCount_V or streamSource_V_1)
begin
    ap_sig_bdd_89 = (~(streamSource_V_1 == ap_const_lv1_0) & ~(ic_wordCount_V == ap_const_lv16_2) & ~(ic_wordCount_V == ap_const_lv16_0) & ~(ap_const_lv1_0 == tmp_phi_fu_226_p4));
end
assign brmerge_fu_403_p2 = (grp_nbreadreq_fu_114_p5 | grp_nbreadreq_fu_126_p5);
assign dataStreams_V_data_V_00_status = (dataStreams_V_data_V_0_empty_n & dataStreams_V_keep_V_0_empty_n & dataStreams_V_last_V_0_empty_n);
assign dataStreams_V_data_V_0_read = dataStreams_V_data_V_00_update;
assign dataStreams_V_data_V_10_status = (dataStreams_V_data_V_1_empty_n & dataStreams_V_keep_V_1_empty_n & dataStreams_V_last_V_1_empty_n);
assign dataStreams_V_data_V_1_read = dataStreams_V_data_V_10_update;
assign dataStreams_V_keep_V_0_read = dataStreams_V_data_V_00_update;
assign dataStreams_V_keep_V_1_read = dataStreams_V_data_V_10_update;
assign dataStreams_V_last_V_0_read = dataStreams_V_data_V_00_update;
assign dataStreams_V_last_V_1_read = dataStreams_V_data_V_10_update;
assign grp_nbreadreq_fu_114_p5 = (dataStreams_V_data_V_0_empty_n & dataStreams_V_keep_V_0_empty_n & dataStreams_V_last_V_0_empty_n);
assign grp_nbreadreq_fu_126_p5 = (dataStreams_V_data_V_1_empty_n & dataStreams_V_keep_V_1_empty_n & dataStreams_V_last_V_1_empty_n);
assign not_tmp_s_fu_409_p2 = (grp_nbreadreq_fu_114_p5 ^ ap_const_lv1_1);
assign outputStream_V_data_V1_status = (outputStream_V_data_V_full_n & outputStream_V_keep_V_full_n & outputStream_V_last_V_full_n);
assign outputStream_V_data_V_write = outputStream_V_data_V1_update;
assign outputStream_V_keep_V_write = outputStream_V_data_V1_update;
assign outputStream_V_last_V_write = outputStream_V_data_V1_update;
assign p_Result_s_fu_447_p5 = {{ap_reg_phiprechg_icmpChecksum_V_1_reg_275pp0_it1}, {ap_reg_phiprechg_p_Val2_s_reg_266pp0_it1[32'd47 : 32'd0]}};
assign p_tmp_s_fu_433_p3 = ((tmp_last_V_5_phi_fu_239_p4)? ap_const_lv16_0: tmp_9_fu_427_p2);
assign tmp_7_nbreadreq_fu_146_p3 = checksumStreams_V_V_1_empty_n;
assign tmp_8_nbreadreq_fu_138_p3 = checksumStreams_V_V_0_empty_n;
assign tmp_9_fu_427_p2 = (ic_wordCount_V + ap_const_lv16_1);


endmodule //icmp_server_insertChecksum

