set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[62]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[38]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[46]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[13]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[36]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[52]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[44]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[60]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[11]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[27]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[19]}]
set_property MARK_DEBUG true [get_nets SHELL/sNTS_MPE_Tcp_TREADY]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_ROLE_MPI_data_TREADY]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[55]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[47]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[22]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[37]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[53]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[45]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[61]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[12]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[28]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[20]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPIif_V_count_V_TVALID]
set_property MARK_DEBUG true [get_nets SHELL/sNts0_MPE_IPmeta_tvalid]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[32]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[9]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[31]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[15]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[56]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[38]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[54]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[46]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[62]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[13]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[29]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[21]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_NTS_Tcp_TREADY]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[41]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[16]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[39]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[55]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[63]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[14]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[22]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_Nts0_IPmeta_tvalid]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[58]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[50]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[34]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[25]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[8]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[40]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[32]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[56]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[48]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[15]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[31]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[23]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[9]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_Nts0_IPmeta_tready]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[43]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[59]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[35]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[18]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[10]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[16]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[41]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[57]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[49]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[33]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[24]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[7]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_ROLE_MPI_data_TLAST]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[52]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[44]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[19]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[17]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[25]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[8]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[42]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[34]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[58]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[50]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[7]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPIif_V_rank_V_TREADY]
set_property MARK_DEBUG true [get_nets SHELL/sROLE_MPE_MPI_data_TREADY]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[37]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[53]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[61]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[12]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[28]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[18]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[26]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[10]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[43]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[35]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[59]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[51]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[8]}]
set_property MARK_DEBUG true [get_nets SHELL/sNts0_MPE_IPmeta_tready]
set_property MARK_DEBUG true [get_nets SHELL/sNTS_MPE_Tcp_TLAST]
set_property MARK_DEBUG true [get_nets SHELL/sMPIif_V_mpi_call_V_TVALID]
set_property MARK_DEBUG true [get_nets SHELL/sMPIif_V_count_V_TREADY]
set_property MARK_DEBUG true [get_nets SHELL/sROLE_MPE_MPI_data_TLAST]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_NTS_Tcp_TLAST]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[47]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_Nts0_IPmeta_tdata[30]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[33]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[40]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_ROLE_MPI_data_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_count_V_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[49]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[57]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[60]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[63]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[2]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[3]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_NTS_Tcp_TVALID]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_ROLE_MPI_data_TKEEP]
set_property MARK_DEBUG true [get_nets SHELL/sMPE_ROLE_MPI_data_TVALID]
set_property MARK_DEBUG true [get_nets SHELL/sMPIif_V_rank_V_TVALID]
set_property MARK_DEBUG true [get_nets SHELL/sNTS_MPE_Tcp_TVALID]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_mpi_call_V_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[36]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[42]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[45]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[48]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[51]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[54]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[7]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[11]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[14]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[17]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[20]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[23]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[26]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[29]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[6]}]
set_property MARK_DEBUG true [get_nets SHELL/sMPIif_V_mpi_call_V_TREADY]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TKEEP[5]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPIif_V_rank_V_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[39]}]
set_property MARK_DEBUG true [get_nets SHELL/sROLE_MPE_MPI_data_TKEEP]
set_property MARK_DEBUG true [get_nets SHELL/sROLE_MPE_MPI_data_TVALID]
set_property MARK_DEBUG true [get_nets {SHELL/sNTS_MPE_Tcp_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[27]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[30]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {SHELL/sMPE_NTS_Tcp_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[21]}]
set_property MARK_DEBUG true [get_nets {SHELL/sNts0_MPE_IPmeta_tdata[24]}]
set_property MARK_DEBUG true [get_nets {SHELL/sROLE_MPE_MPI_data_TDATA[4]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list SHELL/SuperCfg.ETH0/ETH/CORE/IP/U0/xpcs/U0/ten_gig_eth_pcs_pma_shared_clock_reset_block/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {SHELL/sMPE_NTS_Tcp_TDATA[0]} {SHELL/sMPE_NTS_Tcp_TDATA[1]} {SHELL/sMPE_NTS_Tcp_TDATA[2]} {SHELL/sMPE_NTS_Tcp_TDATA[3]} {SHELL/sMPE_NTS_Tcp_TDATA[4]} {SHELL/sMPE_NTS_Tcp_TDATA[5]} {SHELL/sMPE_NTS_Tcp_TDATA[6]} {SHELL/sMPE_NTS_Tcp_TDATA[7]} {SHELL/sMPE_NTS_Tcp_TDATA[8]} {SHELL/sMPE_NTS_Tcp_TDATA[9]} {SHELL/sMPE_NTS_Tcp_TDATA[10]} {SHELL/sMPE_NTS_Tcp_TDATA[11]} {SHELL/sMPE_NTS_Tcp_TDATA[12]} {SHELL/sMPE_NTS_Tcp_TDATA[13]} {SHELL/sMPE_NTS_Tcp_TDATA[14]} {SHELL/sMPE_NTS_Tcp_TDATA[15]} {SHELL/sMPE_NTS_Tcp_TDATA[16]} {SHELL/sMPE_NTS_Tcp_TDATA[17]} {SHELL/sMPE_NTS_Tcp_TDATA[18]} {SHELL/sMPE_NTS_Tcp_TDATA[19]} {SHELL/sMPE_NTS_Tcp_TDATA[20]} {SHELL/sMPE_NTS_Tcp_TDATA[21]} {SHELL/sMPE_NTS_Tcp_TDATA[22]} {SHELL/sMPE_NTS_Tcp_TDATA[23]} {SHELL/sMPE_NTS_Tcp_TDATA[24]} {SHELL/sMPE_NTS_Tcp_TDATA[25]} {SHELL/sMPE_NTS_Tcp_TDATA[26]} {SHELL/sMPE_NTS_Tcp_TDATA[27]} {SHELL/sMPE_NTS_Tcp_TDATA[28]} {SHELL/sMPE_NTS_Tcp_TDATA[29]} {SHELL/sMPE_NTS_Tcp_TDATA[30]} {SHELL/sMPE_NTS_Tcp_TDATA[31]} {SHELL/sMPE_NTS_Tcp_TDATA[32]} {SHELL/sMPE_NTS_Tcp_TDATA[33]} {SHELL/sMPE_NTS_Tcp_TDATA[34]} {SHELL/sMPE_NTS_Tcp_TDATA[35]} {SHELL/sMPE_NTS_Tcp_TDATA[36]} {SHELL/sMPE_NTS_Tcp_TDATA[37]} {SHELL/sMPE_NTS_Tcp_TDATA[38]} {SHELL/sMPE_NTS_Tcp_TDATA[39]} {SHELL/sMPE_NTS_Tcp_TDATA[40]} {SHELL/sMPE_NTS_Tcp_TDATA[41]} {SHELL/sMPE_NTS_Tcp_TDATA[42]} {SHELL/sMPE_NTS_Tcp_TDATA[43]} {SHELL/sMPE_NTS_Tcp_TDATA[44]} {SHELL/sMPE_NTS_Tcp_TDATA[45]} {SHELL/sMPE_NTS_Tcp_TDATA[46]} {SHELL/sMPE_NTS_Tcp_TDATA[47]} {SHELL/sMPE_NTS_Tcp_TDATA[48]} {SHELL/sMPE_NTS_Tcp_TDATA[49]} {SHELL/sMPE_NTS_Tcp_TDATA[50]} {SHELL/sMPE_NTS_Tcp_TDATA[51]} {SHELL/sMPE_NTS_Tcp_TDATA[52]} {SHELL/sMPE_NTS_Tcp_TDATA[53]} {SHELL/sMPE_NTS_Tcp_TDATA[54]} {SHELL/sMPE_NTS_Tcp_TDATA[55]} {SHELL/sMPE_NTS_Tcp_TDATA[56]} {SHELL/sMPE_NTS_Tcp_TDATA[57]} {SHELL/sMPE_NTS_Tcp_TDATA[58]} {SHELL/sMPE_NTS_Tcp_TDATA[59]} {SHELL/sMPE_NTS_Tcp_TDATA[60]} {SHELL/sMPE_NTS_Tcp_TDATA[61]} {SHELL/sMPE_NTS_Tcp_TDATA[62]} {SHELL/sMPE_NTS_Tcp_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {SHELL/sMPE_NTS_Tcp_TKEEP[0]} {SHELL/sMPE_NTS_Tcp_TKEEP[1]} {SHELL/sMPE_NTS_Tcp_TKEEP[2]} {SHELL/sMPE_NTS_Tcp_TKEEP[3]} {SHELL/sMPE_NTS_Tcp_TKEEP[4]} {SHELL/sMPE_NTS_Tcp_TKEEP[5]} {SHELL/sMPE_NTS_Tcp_TKEEP[6]} {SHELL/sMPE_NTS_Tcp_TKEEP[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {SHELL/sMPE_Nts0_IPmeta_tdata[0]} {SHELL/sMPE_Nts0_IPmeta_tdata[1]} {SHELL/sMPE_Nts0_IPmeta_tdata[2]} {SHELL/sMPE_Nts0_IPmeta_tdata[3]} {SHELL/sMPE_Nts0_IPmeta_tdata[4]} {SHELL/sMPE_Nts0_IPmeta_tdata[5]} {SHELL/sMPE_Nts0_IPmeta_tdata[6]} {SHELL/sMPE_Nts0_IPmeta_tdata[7]} {SHELL/sMPE_Nts0_IPmeta_tdata[8]} {SHELL/sMPE_Nts0_IPmeta_tdata[9]} {SHELL/sMPE_Nts0_IPmeta_tdata[10]} {SHELL/sMPE_Nts0_IPmeta_tdata[11]} {SHELL/sMPE_Nts0_IPmeta_tdata[12]} {SHELL/sMPE_Nts0_IPmeta_tdata[13]} {SHELL/sMPE_Nts0_IPmeta_tdata[14]} {SHELL/sMPE_Nts0_IPmeta_tdata[15]} {SHELL/sMPE_Nts0_IPmeta_tdata[16]} {SHELL/sMPE_Nts0_IPmeta_tdata[17]} {SHELL/sMPE_Nts0_IPmeta_tdata[18]} {SHELL/sMPE_Nts0_IPmeta_tdata[19]} {SHELL/sMPE_Nts0_IPmeta_tdata[20]} {SHELL/sMPE_Nts0_IPmeta_tdata[21]} {SHELL/sMPE_Nts0_IPmeta_tdata[22]} {SHELL/sMPE_Nts0_IPmeta_tdata[23]} {SHELL/sMPE_Nts0_IPmeta_tdata[24]} {SHELL/sMPE_Nts0_IPmeta_tdata[25]} {SHELL/sMPE_Nts0_IPmeta_tdata[26]} {SHELL/sMPE_Nts0_IPmeta_tdata[27]} {SHELL/sMPE_Nts0_IPmeta_tdata[28]} {SHELL/sMPE_Nts0_IPmeta_tdata[29]} {SHELL/sMPE_Nts0_IPmeta_tdata[30]} {SHELL/sMPE_Nts0_IPmeta_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {SHELL/sMPE_ROLE_MPI_data_TDATA[0]} {SHELL/sMPE_ROLE_MPI_data_TDATA[1]} {SHELL/sMPE_ROLE_MPI_data_TDATA[2]} {SHELL/sMPE_ROLE_MPI_data_TDATA[3]} {SHELL/sMPE_ROLE_MPI_data_TDATA[4]} {SHELL/sMPE_ROLE_MPI_data_TDATA[5]} {SHELL/sMPE_ROLE_MPI_data_TDATA[6]} {SHELL/sMPE_ROLE_MPI_data_TDATA[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {SHELL/sMPIif_V_count_V_TDATA[0]} {SHELL/sMPIif_V_count_V_TDATA[1]} {SHELL/sMPIif_V_count_V_TDATA[2]} {SHELL/sMPIif_V_count_V_TDATA[3]} {SHELL/sMPIif_V_count_V_TDATA[4]} {SHELL/sMPIif_V_count_V_TDATA[5]} {SHELL/sMPIif_V_count_V_TDATA[6]} {SHELL/sMPIif_V_count_V_TDATA[7]} {SHELL/sMPIif_V_count_V_TDATA[8]} {SHELL/sMPIif_V_count_V_TDATA[9]} {SHELL/sMPIif_V_count_V_TDATA[10]} {SHELL/sMPIif_V_count_V_TDATA[11]} {SHELL/sMPIif_V_count_V_TDATA[12]} {SHELL/sMPIif_V_count_V_TDATA[13]} {SHELL/sMPIif_V_count_V_TDATA[14]} {SHELL/sMPIif_V_count_V_TDATA[15]} {SHELL/sMPIif_V_count_V_TDATA[16]} {SHELL/sMPIif_V_count_V_TDATA[17]} {SHELL/sMPIif_V_count_V_TDATA[18]} {SHELL/sMPIif_V_count_V_TDATA[19]} {SHELL/sMPIif_V_count_V_TDATA[20]} {SHELL/sMPIif_V_count_V_TDATA[21]} {SHELL/sMPIif_V_count_V_TDATA[22]} {SHELL/sMPIif_V_count_V_TDATA[23]} {SHELL/sMPIif_V_count_V_TDATA[24]} {SHELL/sMPIif_V_count_V_TDATA[25]} {SHELL/sMPIif_V_count_V_TDATA[26]} {SHELL/sMPIif_V_count_V_TDATA[27]} {SHELL/sMPIif_V_count_V_TDATA[28]} {SHELL/sMPIif_V_count_V_TDATA[29]} {SHELL/sMPIif_V_count_V_TDATA[30]} {SHELL/sMPIif_V_count_V_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {SHELL/sMPIif_V_mpi_call_V_TDATA[0]} {SHELL/sMPIif_V_mpi_call_V_TDATA[1]} {SHELL/sMPIif_V_mpi_call_V_TDATA[2]} {SHELL/sMPIif_V_mpi_call_V_TDATA[3]} {SHELL/sMPIif_V_mpi_call_V_TDATA[4]} {SHELL/sMPIif_V_mpi_call_V_TDATA[5]} {SHELL/sMPIif_V_mpi_call_V_TDATA[6]} {SHELL/sMPIif_V_mpi_call_V_TDATA[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {SHELL/sMPIif_V_rank_V_TDATA[0]} {SHELL/sMPIif_V_rank_V_TDATA[1]} {SHELL/sMPIif_V_rank_V_TDATA[2]} {SHELL/sMPIif_V_rank_V_TDATA[3]} {SHELL/sMPIif_V_rank_V_TDATA[4]} {SHELL/sMPIif_V_rank_V_TDATA[5]} {SHELL/sMPIif_V_rank_V_TDATA[6]} {SHELL/sMPIif_V_rank_V_TDATA[7]} {SHELL/sMPIif_V_rank_V_TDATA[8]} {SHELL/sMPIif_V_rank_V_TDATA[9]} {SHELL/sMPIif_V_rank_V_TDATA[10]} {SHELL/sMPIif_V_rank_V_TDATA[11]} {SHELL/sMPIif_V_rank_V_TDATA[12]} {SHELL/sMPIif_V_rank_V_TDATA[13]} {SHELL/sMPIif_V_rank_V_TDATA[14]} {SHELL/sMPIif_V_rank_V_TDATA[15]} {SHELL/sMPIif_V_rank_V_TDATA[16]} {SHELL/sMPIif_V_rank_V_TDATA[17]} {SHELL/sMPIif_V_rank_V_TDATA[18]} {SHELL/sMPIif_V_rank_V_TDATA[19]} {SHELL/sMPIif_V_rank_V_TDATA[20]} {SHELL/sMPIif_V_rank_V_TDATA[21]} {SHELL/sMPIif_V_rank_V_TDATA[22]} {SHELL/sMPIif_V_rank_V_TDATA[23]} {SHELL/sMPIif_V_rank_V_TDATA[24]} {SHELL/sMPIif_V_rank_V_TDATA[25]} {SHELL/sMPIif_V_rank_V_TDATA[26]} {SHELL/sMPIif_V_rank_V_TDATA[27]} {SHELL/sMPIif_V_rank_V_TDATA[28]} {SHELL/sMPIif_V_rank_V_TDATA[29]} {SHELL/sMPIif_V_rank_V_TDATA[30]} {SHELL/sMPIif_V_rank_V_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 64 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {SHELL/sNTS_MPE_Tcp_TDATA[0]} {SHELL/sNTS_MPE_Tcp_TDATA[1]} {SHELL/sNTS_MPE_Tcp_TDATA[2]} {SHELL/sNTS_MPE_Tcp_TDATA[3]} {SHELL/sNTS_MPE_Tcp_TDATA[4]} {SHELL/sNTS_MPE_Tcp_TDATA[5]} {SHELL/sNTS_MPE_Tcp_TDATA[6]} {SHELL/sNTS_MPE_Tcp_TDATA[7]} {SHELL/sNTS_MPE_Tcp_TDATA[8]} {SHELL/sNTS_MPE_Tcp_TDATA[9]} {SHELL/sNTS_MPE_Tcp_TDATA[10]} {SHELL/sNTS_MPE_Tcp_TDATA[11]} {SHELL/sNTS_MPE_Tcp_TDATA[12]} {SHELL/sNTS_MPE_Tcp_TDATA[13]} {SHELL/sNTS_MPE_Tcp_TDATA[14]} {SHELL/sNTS_MPE_Tcp_TDATA[15]} {SHELL/sNTS_MPE_Tcp_TDATA[16]} {SHELL/sNTS_MPE_Tcp_TDATA[17]} {SHELL/sNTS_MPE_Tcp_TDATA[18]} {SHELL/sNTS_MPE_Tcp_TDATA[19]} {SHELL/sNTS_MPE_Tcp_TDATA[20]} {SHELL/sNTS_MPE_Tcp_TDATA[21]} {SHELL/sNTS_MPE_Tcp_TDATA[22]} {SHELL/sNTS_MPE_Tcp_TDATA[23]} {SHELL/sNTS_MPE_Tcp_TDATA[24]} {SHELL/sNTS_MPE_Tcp_TDATA[25]} {SHELL/sNTS_MPE_Tcp_TDATA[26]} {SHELL/sNTS_MPE_Tcp_TDATA[27]} {SHELL/sNTS_MPE_Tcp_TDATA[28]} {SHELL/sNTS_MPE_Tcp_TDATA[29]} {SHELL/sNTS_MPE_Tcp_TDATA[30]} {SHELL/sNTS_MPE_Tcp_TDATA[31]} {SHELL/sNTS_MPE_Tcp_TDATA[32]} {SHELL/sNTS_MPE_Tcp_TDATA[33]} {SHELL/sNTS_MPE_Tcp_TDATA[34]} {SHELL/sNTS_MPE_Tcp_TDATA[35]} {SHELL/sNTS_MPE_Tcp_TDATA[36]} {SHELL/sNTS_MPE_Tcp_TDATA[37]} {SHELL/sNTS_MPE_Tcp_TDATA[38]} {SHELL/sNTS_MPE_Tcp_TDATA[39]} {SHELL/sNTS_MPE_Tcp_TDATA[40]} {SHELL/sNTS_MPE_Tcp_TDATA[41]} {SHELL/sNTS_MPE_Tcp_TDATA[42]} {SHELL/sNTS_MPE_Tcp_TDATA[43]} {SHELL/sNTS_MPE_Tcp_TDATA[44]} {SHELL/sNTS_MPE_Tcp_TDATA[45]} {SHELL/sNTS_MPE_Tcp_TDATA[46]} {SHELL/sNTS_MPE_Tcp_TDATA[47]} {SHELL/sNTS_MPE_Tcp_TDATA[48]} {SHELL/sNTS_MPE_Tcp_TDATA[49]} {SHELL/sNTS_MPE_Tcp_TDATA[50]} {SHELL/sNTS_MPE_Tcp_TDATA[51]} {SHELL/sNTS_MPE_Tcp_TDATA[52]} {SHELL/sNTS_MPE_Tcp_TDATA[53]} {SHELL/sNTS_MPE_Tcp_TDATA[54]} {SHELL/sNTS_MPE_Tcp_TDATA[55]} {SHELL/sNTS_MPE_Tcp_TDATA[56]} {SHELL/sNTS_MPE_Tcp_TDATA[57]} {SHELL/sNTS_MPE_Tcp_TDATA[58]} {SHELL/sNTS_MPE_Tcp_TDATA[59]} {SHELL/sNTS_MPE_Tcp_TDATA[60]} {SHELL/sNTS_MPE_Tcp_TDATA[61]} {SHELL/sNTS_MPE_Tcp_TDATA[62]} {SHELL/sNTS_MPE_Tcp_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {SHELL/sNTS_MPE_Tcp_TKEEP[0]} {SHELL/sNTS_MPE_Tcp_TKEEP[1]} {SHELL/sNTS_MPE_Tcp_TKEEP[2]} {SHELL/sNTS_MPE_Tcp_TKEEP[3]} {SHELL/sNTS_MPE_Tcp_TKEEP[4]} {SHELL/sNTS_MPE_Tcp_TKEEP[5]} {SHELL/sNTS_MPE_Tcp_TKEEP[6]} {SHELL/sNTS_MPE_Tcp_TKEEP[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {SHELL/sNts0_MPE_IPmeta_tdata[0]} {SHELL/sNts0_MPE_IPmeta_tdata[1]} {SHELL/sNts0_MPE_IPmeta_tdata[2]} {SHELL/sNts0_MPE_IPmeta_tdata[3]} {SHELL/sNts0_MPE_IPmeta_tdata[4]} {SHELL/sNts0_MPE_IPmeta_tdata[5]} {SHELL/sNts0_MPE_IPmeta_tdata[6]} {SHELL/sNts0_MPE_IPmeta_tdata[7]} {SHELL/sNts0_MPE_IPmeta_tdata[8]} {SHELL/sNts0_MPE_IPmeta_tdata[9]} {SHELL/sNts0_MPE_IPmeta_tdata[10]} {SHELL/sNts0_MPE_IPmeta_tdata[11]} {SHELL/sNts0_MPE_IPmeta_tdata[12]} {SHELL/sNts0_MPE_IPmeta_tdata[13]} {SHELL/sNts0_MPE_IPmeta_tdata[14]} {SHELL/sNts0_MPE_IPmeta_tdata[15]} {SHELL/sNts0_MPE_IPmeta_tdata[16]} {SHELL/sNts0_MPE_IPmeta_tdata[17]} {SHELL/sNts0_MPE_IPmeta_tdata[18]} {SHELL/sNts0_MPE_IPmeta_tdata[19]} {SHELL/sNts0_MPE_IPmeta_tdata[20]} {SHELL/sNts0_MPE_IPmeta_tdata[21]} {SHELL/sNts0_MPE_IPmeta_tdata[22]} {SHELL/sNts0_MPE_IPmeta_tdata[23]} {SHELL/sNts0_MPE_IPmeta_tdata[24]} {SHELL/sNts0_MPE_IPmeta_tdata[25]} {SHELL/sNts0_MPE_IPmeta_tdata[26]} {SHELL/sNts0_MPE_IPmeta_tdata[27]} {SHELL/sNts0_MPE_IPmeta_tdata[28]} {SHELL/sNts0_MPE_IPmeta_tdata[29]} {SHELL/sNts0_MPE_IPmeta_tdata[30]} {SHELL/sNts0_MPE_IPmeta_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {SHELL/sROLE_MPE_MPI_data_TDATA[0]} {SHELL/sROLE_MPE_MPI_data_TDATA[1]} {SHELL/sROLE_MPE_MPI_data_TDATA[2]} {SHELL/sROLE_MPE_MPI_data_TDATA[3]} {SHELL/sROLE_MPE_MPI_data_TDATA[4]} {SHELL/sROLE_MPE_MPI_data_TDATA[5]} {SHELL/sROLE_MPE_MPI_data_TDATA[6]} {SHELL/sROLE_MPE_MPI_data_TDATA[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list SHELL/sMPE_Nts0_IPmeta_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list SHELL/sMPE_Nts0_IPmeta_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list SHELL/sMPE_NTS_Tcp_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list SHELL/sMPE_NTS_Tcp_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list SHELL/sMPE_NTS_Tcp_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list SHELL/sMPE_ROLE_MPI_data_TKEEP]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list SHELL/sMPE_ROLE_MPI_data_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list SHELL/sMPE_ROLE_MPI_data_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list SHELL/sMPE_ROLE_MPI_data_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list SHELL/sMPIif_V_count_V_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list SHELL/sMPIif_V_count_V_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list SHELL/sMPIif_V_mpi_call_V_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list SHELL/sMPIif_V_mpi_call_V_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list SHELL/sMPIif_V_rank_V_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list SHELL/sMPIif_V_rank_V_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list SHELL/sNts0_MPE_IPmeta_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list SHELL/sNts0_MPE_IPmeta_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list SHELL/sNTS_MPE_Tcp_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list SHELL/sNTS_MPE_Tcp_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list SHELL/sNTS_MPE_Tcp_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list SHELL/sROLE_MPE_MPI_data_TKEEP]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list SHELL/sROLE_MPE_MPI_data_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list SHELL/sROLE_MPE_MPI_data_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list SHELL/sROLE_MPE_MPI_data_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
